<?php
namespace Aura\SanitizeHtml\View\Helper;

use Aura\SanitizeHtml\Sanitize as SanitizeHtml;

/**
 * Test class for Sanitize.
 * Generated by PHPUnit on 2012-09-14 at 00:25:25.
 */
class SanitizeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Sanitize
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new Sanitize(new SanitizeHtml);
    }

    public function test__invoke()
    {
        $str      = '<b> hello world</b>';
        $sanitize = $this->object;
        $this->assertEquals($str, $sanitize($str));
    }
}
